version: "3"

x-env: &env
  TZ: Asia/Tokyo
  MYSQL_ROOT_PASSWORD: docker_root_password
  MYSQL_USER: docker_user
  MYSQL_PASSWORD: docker_password
  MYSQL_DATABASE: whos-who
  DATABASE_URL: mysql://docker_user:docker_password@mysql-prod:3306/whos-who
  SERVER_APOLLO_URI: http://backend:3301
  PUBLIC_APOLLO_URI: http://localhost:3301

x-ts-base: &ts-base
  volumes:
    - ./typescript:/app
    - /app/node_modules
    - /app/packages/backend/node_modules
    - /app/packages/backend/dist
    - /app/packages/frontend/node_modules
    - /app/packages/frontend/.next
    - /app/packages/frontend/.env.production.local

services:
  mysql-prod:
    image: mysql:8.0
    command: mysqld
    environment:
      <<: *env
    ports:
      - 4306:3306
    volumes:
      - ./database/mysql/data:/var/lib/mysql
      - ./database/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  backend-prod:
    <<: *ts-base
    build:
      context: ./typescript
      dockerfile: ./packages/backend/Dockerfile.prod
    tty: true
    environment:
      <<: *env
    depends_on:
      - mysql-prod
    ports:
      - "3301:3301"

  frontend-prod:
    <<: *ts-base
    build:
      context: ./typescript
      dockerfile: ./packages/frontend/Dockerfile.prod
    tty: true
    environment:
      <<: *env
      PORT: 3401
    depends_on:
      - backend-prod
    ports:
      - "3401:3401"

volumes:
  mysql-prod:
    driver: local
  backend-prod:
    driver: local
  frontend-prod:
    driver: local
