version: "3"

x-base: &base
  environment:
    TZ: Asia/Tokyo
    MYSQL_ROOT_PASSWORD: docker_root_password
    MYSQL_USER: docker_user
    MYSQL_PASSWORD: docker_password
    MYSQL_DATABASE: whos-who
    DATABASE_URL: mysql://docker_user:docker_password@mysql-prod:3306/whos-who
    SERVER_APOLLO_URI: http://backend:3301
    PUBLIC_APOLLO_URI: http://localhost:3301

x-ts-base: &ts-base
  <<: *base
  volumes:
    - ./typescript:/app
    - /app/node_modules
    - /app/packages/backend/node_modules
    - /app/packages/backend/dist
    - /app/packages/frontend/node_modules
    - /app/packages/frontend/.next

services:
  mysql-prod:
    <<: *base
    image: mysql:8.0
    command: mysqld
    ports:
      - 4306:3306
    volumes:
      - ./database/mysql/data:/var/lib/mysql
      - ./database/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  backend-prod:
    <<: *ts-base
    build:
      context: ./typescript
      dockerfile: ./packages/backend/Dockerfile.prod
    tty: true
    depends_on:
      - mysql-prod
    ports:
      - "3301:3301"

  frontend-prod:
    <<: *ts-base
    build:
      context: ./typescript
      dockerfile: ./packages/frontend/Dockerfile.prod
    tty: true
    environment:
      PORT: 3401
    depends_on:
      - backend-prod
    ports:
      - "3401:3401"

volumes:
  mysql-prod:
    driver: local
  backend-prod:
    driver: local
  frontend-prod:
    driver: local
