version: "3"

x-base: &base
  environment:
    TZ: Asia/Tokyo
    MYSQL_ROOT_PASSWORD: docker_root_password
    MYSQL_USER: docker_user
    MYSQL_PASSWORD: docker_password
    MYSQL_DATABASE: whos-who
    DATABASE_URL: mysql://docker_user:docker_password@mysql:3306/whos-who
    SERVER_APOLLO_URI: http://backend:3300
    PUBLIC_APOLLO_URI: http://localhost:3300

x-ts-base: &ts-base
  <<: *base
  volumes:
    - ./typescript:/app
    - /app/node_modules
    - /app/packages/backend/node_modules
    - /app/packages/backend/dist
    - /app/packages/frontend/node_modules
    - /app/packages/frontend/.next

services:
  mysql:
    <<: *base
    image: mysql:8.0
    command: mysqld
    ports:
      - 4306:3306
    volumes:
      - ./database/mysql/data:/var/lib/mysql
      - ./database/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  backend:
    <<: *ts-base
    build:
      context: ./typescript
      dockerfile: ./packages/backend/Dockerfile
    command: yarn @backend start
    tty: true
    depends_on:
      - mysql
    ports:
      - "3300:3300"

  frontend:
    <<: *ts-base
    build:
      context: ./typescript
      dockerfile: ./packages/frontend/Dockerfile
    command: yarn @frontend start
    tty: true
    depends_on:
      - backend
    ports:
      - "3400:3400"

volumes:
  mysql:
    driver: local
  backend:
    driver: local
  frontend:
    driver: local
